/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package contact;

import java.util.ArrayList;

/**
 *
 * @author jordancarthy
 */
public class ContactGui extends javax.swing.JFrame {
    ArrayList <Contact> AddressBook;
    /**
     * Creates new form ContactGui
     */
    public ContactGui() {
        AddressBook = new ArrayList<>();
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        addressLBL = new javax.swing.JLabel();
        emailLBL = new javax.swing.JLabel();
        nameLBL = new javax.swing.JLabel();
        surnameLBL = new javax.swing.JLabel();
        phoneLBL = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        surnameTF = new javax.swing.JTextField();
        emailTF = new javax.swing.JTextField();
        phoneTF = new javax.swing.JTextField();
        addressTF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        addBTN = new javax.swing.JButton();
        searchBTN = new javax.swing.JButton();
        deleteBTN = new javax.swing.JButton();
        companyLBL = new javax.swing.JLabel();
        companyTF = new javax.swing.JTextField();
        regularRBTN = new javax.swing.JRadioButton();
        businessRBTN = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addressLBL.setText("Address");
        getContentPane().add(addressLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        emailLBL.setText("Email");
        getContentPane().add(emailLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        nameLBL.setText("Name");
        getContentPane().add(nameLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        surnameLBL.setText("Surname");
        getContentPane().add(surnameLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        phoneLBL.setText("Phone");
        getContentPane().add(phoneLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));
        getContentPane().add(nameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 100, -1));

        surnameTF.setText(" ");
        getContentPane().add(surnameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 100, -1));

        emailTF.setText(" ");
        getContentPane().add(emailTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 100, -1));

        phoneTF.setText(" ");
        getContentPane().add(phoneTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 100, -1));

        addressTF.setText(" ");
        getContentPane().add(addressTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 100, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 280, 120));

        addBTN.setText("Add");
        addBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTNActionPerformed(evt);
            }
        });
        getContentPane().add(addBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, -1, -1));

        searchBTN.setText("Search");
        searchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBTNActionPerformed(evt);
            }
        });
        getContentPane().add(searchBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, -1, -1));

        deleteBTN.setText("Delete");
        getContentPane().add(deleteBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, -1, -1));

        companyLBL.setText("Company");
        getContentPane().add(companyLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        companyTF.setText(" ");
        getContentPane().add(companyTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 100, -1));

        buttonGroup.add(regularRBTN);
        regularRBTN.setText("Regular");
        regularRBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regularRBTNActionPerformed(evt);
            }
        });
        getContentPane().add(regularRBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, -1));

        buttonGroup.add(businessRBTN);
        businessRBTN.setText("Business");
        getContentPane().add(businessRBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addBTNActionPerformed

    private void searchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBTNActionPerformed

    private void regularRBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regularRBTNActionPerformed
        // TODO add your handling code here:
        companyLBL.setVisible(false);
        companyTF.setVisible(false);
        
    }//GEN-LAST:event_regularRBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContactGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContactGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContactGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContactGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContactGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBTN;
    private javax.swing.JLabel addressLBL;
    private javax.swing.JTextField addressTF;
    private javax.swing.JRadioButton businessRBTN;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JLabel companyLBL;
    private javax.swing.JTextField companyTF;
    private javax.swing.JButton deleteBTN;
    private javax.swing.JLabel emailLBL;
    private javax.swing.JTextField emailTF;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel nameLBL;
    private javax.swing.JTextField nameTF;
    private javax.swing.JLabel phoneLBL;
    private javax.swing.JTextField phoneTF;
    private javax.swing.JRadioButton regularRBTN;
    private javax.swing.JButton searchBTN;
    private javax.swing.JLabel surnameLBL;
    private javax.swing.JTextField surnameTF;
    // End of variables declaration//GEN-END:variables
}
